import type { Metadata } from "next";
import "./globals.css";
import { Toaster } from "@/components/ui/toaster";
import { Poppins, Paytone_One } from "next/font/google";
import GlobalProvider from "@/components/organism/GlobalProvider";

export const metadata: Metadata = {
  title: "Apotek Management",
  description: "Generated by create next app",
};

const poppins = Poppins({
  subsets: ["latin"],
  display: "swap",
  weight: ["200", "300", "400", "500", "600", "700", "800"],
  variable: "--font-poppins",
});

const paytone = Paytone_One({
  subsets: ["latin"],
  display: "swap",
  weight: ["400"],
  variable: "--font-paytone",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${poppins.variable} ${paytone.variable} antialiased`}
    >
      <body>
        <GlobalProvider>
          <main className="font-poppins">{children}</main>
          <Toaster />
        </GlobalProvider>
      </body>
    </html>
  );
}
